[program:icvc]
command=/home/icvc_kg/.cache/pypoetry/virtualenvs/icvc-official-pgjkpjNj-py3.10/bin/gunicorn config.wsgi:application -c /var/www/icvc_official/config/deploy/gunicorn.conf.py
directory=/var/www/icvc_official
user=root
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/debug.icvc.log
